language: cpp

compiler:
  - g++
  - clang++

os: linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-7
  env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - g++ -o file_recreation2 file_recreation2.cpp
  - ./file_recreation2 dictionary2.txt Examples/ex1.txt
  - ./file_recreation2 dictionary2.txt Examples/ex2.txt
  - ./file_recreation2 dictionary2.txt Examples/ex3.txt
  - ./file_recreation2 dictionary2.txt Examples/ex4.txt
  - ./file_recreation2 dictionary2.txt Examples/ex5.txt

notifications:
  email: false